
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */


/**
 *
 * @author User
 */
public class NextInfo extends javax.swing.JFrame {

    /**
     * Creates new form NextInfo
     */
    public NextInfo() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        j1 = new javax.swing.JTextField();
        j3 = new javax.swing.JTextField();
        j5 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        j4 = new javax.swing.JTextField();
        j6 = new javax.swing.JTextField();
        j2 = new javax.swing.JTextField();
        j1a = new javax.swing.JTextField();
        j6a = new javax.swing.JTextField();
        j5a = new javax.swing.JTextField();
        j2b = new javax.swing.JTextField();
        j2a = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        prog1 = new javax.swing.JTextField();
        prog2 = new javax.swing.JTextField();
        j1b = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Educational Background");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 28, -1, -1));

        jLabel2.setFont(new java.awt.Font("Georgia", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Elementary");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 67, -1, -1));

        jLabel3.setFont(new java.awt.Font("Georgia", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Secondary");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 213, -1, 26));

        jLabel4.setFont(new java.awt.Font("Georgia", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Tertiary");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, -1, -1));
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, -1));

        jLabel6.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("School Name");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 101, -1, -1));

        jLabel7.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("School Name");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 245, -1, -1));

        jLabel8.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("School Name");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 384, -1, -1));
        getContentPane().add(j1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 124, 197, -1));
        getContentPane().add(j3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 268, 197, -1));
        getContentPane().add(j5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 407, 197, -1));

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Year");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(312, 101, -1, -1));

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Year");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(312, 245, -1, -1));

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Year");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(313, 384, -1, -1));
        getContentPane().add(j4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 296, 197, -1));
        getContentPane().add(j6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 435, 197, -1));

        j2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j2ActionPerformed(evt);
            }
        });
        getContentPane().add(j2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 152, 197, -1));

        j1a.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j1aActionPerformed(evt);
            }
        });
        getContentPane().add(j1a, new org.netbeans.lib.awtextra.AbsoluteConstraints(278, 124, 100, -1));

        j6a.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j6aActionPerformed(evt);
            }
        });
        getContentPane().add(j6a, new org.netbeans.lib.awtextra.AbsoluteConstraints(278, 435, 100, -1));

        j5a.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j5aActionPerformed(evt);
            }
        });
        getContentPane().add(j5a, new org.netbeans.lib.awtextra.AbsoluteConstraints(278, 407, 100, -1));

        j2b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j2bActionPerformed(evt);
            }
        });
        getContentPane().add(j2b, new org.netbeans.lib.awtextra.AbsoluteConstraints(278, 296, 100, -1));

        j2a.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j2aActionPerformed(evt);
            }
        });
        getContentPane().add(j2a, new org.netbeans.lib.awtextra.AbsoluteConstraints(278, 268, 100, -1));

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Program");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(464, 384, -1, -1));

        prog1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prog1ActionPerformed(evt);
            }
        });
        getContentPane().add(prog1, new org.netbeans.lib.awtextra.AbsoluteConstraints(455, 407, 100, -1));

        prog2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prog2ActionPerformed(evt);
            }
        });
        getContentPane().add(prog2, new org.netbeans.lib.awtextra.AbsoluteConstraints(455, 435, 100, -1));

        j1b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j1bActionPerformed(evt);
            }
        });
        getContentPane().add(j1b, new org.netbeans.lib.awtextra.AbsoluteConstraints(278, 144, 100, 30));

        jButton1.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        jButton1.setText("SUBMIT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 400, 130, 51));

        jLabel14.setIcon(new javax.swing.ImageIcon("C:\\Users\\QCU\\Documents\\NetBeansProjects\\qwerty\\Ecommunity\\src\\main\\Pics\\189252.png")); // NOI18N
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel14MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 20, -1, -1));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/nextinfooo.jpg"))); // NOI18N
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -180, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void j2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j2ActionPerformed

    private void j1aActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j1aActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j1aActionPerformed

    private void j6aActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j6aActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j6aActionPerformed

    private void j5aActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j5aActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j5aActionPerformed

    private void j2bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j2bActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j2bActionPerformed

    private void j2aActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j2aActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j2aActionPerformed

    private void prog1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prog1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prog1ActionPerformed

    private void j1bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j1bActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j1bActionPerformed

    private void prog2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prog2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prog2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     String name = j1.getText();
    String name1= j2.getText();
    String name2 = j3.getText();
    String name3 = j4.getText();
    String year = j1a.getText();
    String year2 = j1b.getText();
    String year3 = j2a.getText();
    String year4 = j2b.getText();
    String name4 = j5.getText();
    String name5 = j6.getText();
    String year5 = j5a.getText();
    String year6 = j6a.getText();
    String prog = prog1.getText();
    String progb = prog2.getText();
    
    try {
        Class.forName("com.mysql.cj.jdbc.Driver");
        java.sql.Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/test", "root", "jefflopez");

        // Corrected SQL statement with the right number of placeholders
        String query = "INSERT INTO nextinfo (name, name1, name2, name3, year, year2, year3, year4, name4, name5, year5, year6, prog, progb) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";
        PreparedStatement s1 = con.prepareStatement(query);

        // Set the parameters for the query
        s1.setString(1, name);
        s1.setString(2, name1);
        s1.setString(3, name2);
        s1.setString(4, name3);
        s1.setString(5, year);
        s1.setString(6, year2);
        s1.setString(7, year3);
        s1.setString(8, year4);
        s1.setString(9, name4);
        s1.setString(10, name5);
        s1.setString(11, year5);
        s1.setString(12, year6);
        s1.setString(13, prog);
        s1.setString(14, progb);

        // Execute the update
        s1.executeUpdate();
        con.close();

        JOptionPane.showMessageDialog(this, "REGISTERED");
    } catch (java.sql.SQLException ex) {
        Logger.getLogger(PersonalInfo.class.getName()).log(Level.SEVERE, null, ex);
    } catch (ClassNotFoundException ex) {
        Logger.getLogger(PersonalInfo.class.getName()).log(Level.SEVERE, null, ex);
    

this.dispose();
        NextInfo m = new NextInfo();
                m.setVisible(true);
                m.pack();
                m.setLocationRelativeTo(null);
    
    }                                          
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseClicked
 this.dispose();
        AAAMain m = new AAAMain();
                m.setVisible(true);
                m.pack();
                m.setLocationRelativeTo(null);    }//GEN-LAST:event_jLabel14MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NextInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NextInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NextInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NextInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NextInfo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField j1;
    private javax.swing.JTextField j1a;
    private javax.swing.JTextField j1b;
    private javax.swing.JTextField j2;
    private javax.swing.JTextField j2a;
    private javax.swing.JTextField j2b;
    private javax.swing.JTextField j3;
    private javax.swing.JTextField j4;
    private javax.swing.JTextField j5;
    private javax.swing.JTextField j5a;
    private javax.swing.JTextField j6;
    private javax.swing.JTextField j6a;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField prog1;
    private javax.swing.JTextField prog2;
    // End of variables declaration//GEN-END:variables
}
